---
- hosts: web
  tasks:
  - name: copy file
    copy:
     src: passwd
     dest: /tmp/passwd
  - name: Replace example
    replace:
     path: /tmp/passwd
     regexp: 'timed'
     replace: "shririta"
