---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
  - name: start the ansible test service
    service:
      name: firewalld
      enabled: yes
      state: started
    register: enable_result

  - name: assert that the service was enabled and changes reported
    assert:
      that:
        - "enable_result.enabled == true"
        - "enable_result is changed"

  - debug:
      var: ansible_facts.services["firewalld.service"].state

  - name: disable the ansible test service
    service:
      name: firewalld
      state: stopped
      enabled: no
    register: start_result

  - name: assert that the service was stopped
    assert:
      that:
        - "start_result.state == 'stopped'"
        - "start_result is changed"

  - debug:
      var: ansible_facts.services["firewalld.service"].state

  - name: Populate service facts
    service_facts:

  - name: get firewalld.service service's state
    debug:
      var: services['firewalld.service'].state

  - name: firewalld.service service's running state should be \"inactive\"
    assert:
      that: "services['firewalld.service'].state == 'inactive'"
