---
- hosts: all
  become: yes

  vars:
    my_version: 1.2.3

  tasks:
  - name: check the version
    debug:
      msg: "my_version is higher than 1.0.0"
    when: my_version is version('1.0.0', '>')
