---
- hosts: web
  become: yes
  gather_facts: no

  vars:
    apps_disk: /dev/sdc
    apps_vg: vg_data
    apps_lv: magnum

  tasks:
  - name: add disk to the system
    parted:
      device: "{{ apps_disk }}"
      number: 1
      flags: [ lvm ]
      state: present

  - name: create VG
    lvg:
      vg: "{{ apps_vg }}"
      pvs: "{{ apps_disk }}1"

  - name: create LV
    lvol:
      vg: "{{ apps_vg }}"
      lv: "{{ apps_lv }}"
      shrink: false
      size: 100%FREE

  - name: create filesystem
    filesystem:
      fstype: xfs
      dev: /dev/{{ apps_vg }}/{{ apps_lv }}

  - name: mount point
    mount:
      path: /apps/{{ apps_lv }}
      src: /dev/{{ apps_vg }}/{{ apps_lv }}
      fstype: xfs
      state: mounted
