---
- hosts: web
  become: yes
  gather_facts: no

  vars:
    apps_disk: /dev/sdc
    apps_vg: vg_data
    apps_lv: magnum

  tasks:
  - name: unmount the share
    mount:
      path: /apps/magnum
      src: /dev/{{ apps_vg }}/{{ apps_lv }}
      fstype: xfs
      state: unmounted

  - name: delete LV
    lvol:
      vg: "{{ apps_vg }}"
      lv: "{{ apps_lv }}"
      size: 100%FREE
      state: absent
      force: yes

  - name: delete VG
    lvg:
      vg: "{{ apps_vg }}"
      pvs: /dev/sdc1
      state: absent

  - name: Disk to remove from the system
    parted:
      device: /dev/sdc
      number: 1
      flags: [ lvm ]
      state: absent
