---
- hosts: web
  become: yes
  gather_facts: false

  # environment:
  #   kaka: Hanuman

  #vars:
  #  kaka: Hanuman

  tasks:
  - name: read the profile files
    shell: source /etc/profile
    become_user: test1

  - name: get the output again
    command: /bin/echo $kaka
    become: true
    become_user: test1
    register: ki

  - debug: var=ki.stdout
